version: '3.1'

services:
  backend:
    build: ./Backend
    ports:
      - "5000:80"
    volumes:
      - ./Backend:/app
    networks:
      my-network

  database:
    build: ./DataBase
    ports:
      - "5001:80"
    depends_on:
      - backend
      - socketio
    volumes:
      - ./DataBase:/app
    networks:
      my-network

  frontend:
    build: ./Frontend
    ports:
      - "80:80"
    depends_on:
      - database
      - socketio
    volumes:
      - ./Frontend:/app
    networks:
      my-network

  socketio:
    build: ./socketio
    ports:
      - "5004:80"
    volumes:
      - ./socketio:/app
    networks:
      my-network
        
networks:
  my-network:
    driver: bridge
