version: '3.1'
services:

  db-nginx:
    image: nginx:1.15
    container_name: db-nginx
    volumes:
      - ./DataBase/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 5001:80
    networks:
      - my-network
    depends_on:
      - database
  database:
    build:
      context: ./DataBase
      dockerfile: Dockerfile
    container_name: database
    volumes:
      - ./DataBase:/app
    networks:
      my-network:
        aliases:
          - database-app
    depends_on:
      - benginx
      
      
  benginx:
    image: nginx:1.15
    container_name: benginx
    volumes:
      - ./Backend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 5000:80
    networks:
      - my-network
    depends_on:
      - backend
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./Backend:/app
    networks:
      my-network:
        aliases:
          - backend-app
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./Frontend:/app
    ports:
      - "80:80"
    networks:
      my-network:
        aliases:
          - frontend-app
    depends_on:
      - db-nginx

networks:
  my-network: