version: '3.1'

services:
  backend:
    build: ./Backend
    ports:
      - "5000:80"
    volumes:
      - ./Backend:/app
    networks:
      my-network:
        ipv4_address: 172.18.0.3

  database:
    build: ./DataBase
    ports:
      - "5001:80"
    depends_on:
      - backend
      - socketio
    volumes:
      - ./DataBase:/app
    networks:
      my-network:
        ipv4_address: 172.18.0.4

  frontend:
    build: ./Frontend
    ports:
      - "80:80"
    depends_on:
      - database
      - socketio
    volumes:
      - ./Frontend:/app
    networks:
      my-network:
        ipv4_address: 172.18.0.5

  socketio:
    build: ./socketio
    ports:
      - "5004:80"
    volumes:
      - ./socketio:/app
    networks:
      my-network:
        ipv4_address: 172.18.0.2
        
networks:
  my-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
